title: Alex Giles # your name (or website title) here
logo: "/images/0.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Test
  <br><br>
  Over the past four years as a physics major at Rensselaer Polytechnic Institute I have developed a working knowledge of linear algebra, statistics, advanced calculus, complex variables, and other branches of higher mathematics. Additionally, I have become proficient with multiple programming and query languages including C++, Java, SQL, and Python.

Technology is one of my true passions and I enjoy working out the gritty details and sometimes frustrating bugs. However, my greatest assets are my adaptability and willingness to learn any skills needed to help accomplish my goals in creating revolutionary software. 
  <br><br>
  <a href="https://www.linkedin.com/in/alexander-giles-ba0436179/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
