title: Alex Giles # your name (or website title) here
logo: "/images/0.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Test
  <br><br>
  hello 
  <br><br>
  <a href="https://www.linkedin.com/in/alexander-giles-ba0436179/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
